/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function readPlugins(pathPlugin: string): Array<string>
export interface CommandResult {
  file: string
  trigger: string
}
export declare function matchingPlugin(message: string, commands: Array<[string, Array<string>, Array<string>]>): CommandResult | null
