/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function readPlugins(pathPlugin: string): Array<string>
export declare function matchingPlugin(command: string, triggers: Array<string>, prefixes: Array<string>): boolean
